### PR TITLE
adds regional / themed templates

### PR DESCRIPTION
**Pull request by ksatirli**
this adds regional templates for the Summer 2021 editions

### CODE REVIEW

**Review by eveld — COMMENTED** [review]
In the other directories, the sample generated images are placed in the example folder.

Instead of creating a template for each edition, it would be nicer to use a variable to set the different values instead.

This would make the number of templates a lot lower, because there would just be:
- hashitalks_email.hcl
- hashitalks.hcl (what does this actually generate?)
- hashitalks_speaker.hcl
- hashitalks_speakers_obs.hcl
- hashitalks_youtube.hcl

**Comment by ksatirli** [comment]
> In the other directories, the sample generated images are placed in the example folder.

I didn't include any examples (yet), because I wasn't sure that that made sense (given that this is a generator and we should, in theory, be able to generate the same image with the same configuration.)

The included images (in PNG format) are the samples I've received from upstream, which are then used to generate specific images. Happy to remove them, though that will make using the templates more cumbersome, as the images would have to be retrieved, first.

> Instead of creating a template for each edition, it would be nicer to use a variable to set the different values instead.

Happy to clean up my templates to use variables - I can move all values to a CSV and read them from there (and commit that file).

Does that work?

**Comment by eveld** [comment]
I think we need to find a good way to share source images. Some can just be added to the templates themselves, but others have licenses on them so they can't all be added. How would we deal with public/private assets?

As for the variables, please add them, but the csv file is more an implementation of the template than the actual template itself.
Where should that data live?

**Comment by ksatirli** [comment]
@eveld I've removed the extraneous files and updated / expanded the single line script. 

the way I've set it up:

1.) A shell script with a handful of variables, these get re-used for the various HCL files. This is (in my view) the simplest and cleanest way to make event-specific configs that are immediately runable.

2.) an updated email template; called through the shell script and outputting with and without URL / date

This should make it more manageable

**Pull request closed without merging**
